# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    zip -r $(Build.ArtifactStagingDirectory)/test.zip $(System.DefaultWorkingDirectory)
  displayName: 'npm install and build'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/test.zip'
    artifactName: testzip

#- task: AzureRmWebAppDeployment@4
#  inputs:
#    connectionType: 'AzureRM'
#    azureSubscription: test
#    appType: 'webAppLinux'
#    webAppName: 'agarioclone'
#    packageForLinux: '$(System.DefaultWorkingDirectory)/*.zip'